name: ML Model Deployment

on:
  workflow_dispatch:
    inputs:
      MODEL_NAME:
        description: "Name of the model"
        required: true
      MODEL_VERSION:
        description: "Version of the model"
        required: true
      S3_BUCKET_NAME:
        description: "S3 bucket name"
        required: true
      EXPERIMENT_ID:
        description: "MLFlow experiment ID"
        required: true
      RUN_ID:
        description: "MLflow Run ID"
        required: true

run-name: ml-model-deployment-${{ inputs.MODEL_NAME }}-${{ inputs.MODEL_VERSION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print input values
        run: |
          echo "INPUT VALUES:"
          echo "S3_BUCKET_NAME = ${{ inputs.S3_BUCKET_NAME }}"
          echo "EXPERIMENT_ID  = ${{ inputs.EXPERIMENT_ID }}"
          echo "RUN_ID         = ${{ inputs.RUN_ID }}"
          echo "MODEL_NAME     = ${{ inputs.MODEL_NAME }}"
          echo "MODEL_VERSION  = ${{ inputs.MODEL_VERSION }}"

      - name: Intentional failure
        run: |
          echo "This step will cause the workflow to fail."
          exit 1  # Non-zero exit code will fail the step
