name: Deploy Model

on:
  workflow_dispatch:
    inputs:
      experiment_id:
        description: "Experiment ID"
        required: true
      run_id:
        description: "Run ID"
        required: true
      compute_type:
        description: "Compute size (small, medium, large)"
        required: true
      model_name:
        description: "model name"
        required: true
      model_versison:
        description: "model version"
        required: true
run-name: Deploy-${{ inputs.model_name }}-${{ inputs.model_version }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Experiment ID: ${{ github.event.inputs.experiment_id }}"
          echo "Run ID: ${{ github.event.inputs.run_id }}"
          echo "Compute Type: ${{ github.event.inputs.compute_type }}"
          echo "Compute Type: ${{ github.event.inputs.model_name }}"
          echo "Compute Type: ${{ github.event.inputs.model_version }}"
