name: ML Model Deployment
on:
  workflow_dispatch:
    inputs:
      MODEL_NAME:
        description: "Name of the model"
        required: true
      MODEL_VERSION:
        description: "Version of the model"
        required: true
      S3_BUCKET_NAME:
        description: "S3 bucket name"
        required: true
      EXPERIMENT_ID:
        description: "MLFlow experiment ID"
        required: true
      RUN_ID:
        description: "MLflow Run ID"
        required: true
      TERRAFORM_OPERATION:
        description: "Terraform operation: create or destroy"
        required: true

run-name: ml-model-deployment-${{ inputs.MODEL_NAME }}-${{ inputs.MODEL_VERSION }}-${{ inputs.TERRAFORM_OPERATION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print input values
        run: |
          echo "INPUT VALUES:"
          echo "S3_BUCKET_NAME = ${{ inputs.S3_BUCKET_NAME }}"
          echo "TERRAFORM_OPERATION = ${{ inputs.TERRAFORM_OPERATION }}"
          echo "EXPERIMENT_ID  = ${{ inputs.EXPERIMENT_ID }}"
          echo "RUN_ID         = ${{ inputs.RUN_ID }}"
          echo "MODEL_NAME     = ${{ inputs.MODEL_NAME }}"
          echo "MODEL_VERSION  = ${{ inputs.MODEL_VERSION }}"
